### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by alicangunduz** [alicangunduz/dernek-yonetim#1]
- [ ] Tema 
- [ ]  Örnek yazılımlar üzerinden özellik listesi oluşturulması
- [ ] Özelliklerin listelenmesi
- [ ] Veritabanının tasarlanması
- [ ] Tema üzerinden ilgili sayfaların tasarımının oluşturulması
- [ ] Koda dökümünün tamamlanması
- [ ] Son kullanıcının kurabilmesi için kapsamlı anlatım metni
- [ ] Son kullanıcının kurabilmesi için kapsamlı anlatım videosu
